// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2eCrAhpshFdyU2ie90nq41riZcyqk6s8',
    appId: '1:833233602830:web:dcde3a1aa1fe977455af5f',
    messagingSenderId: '833233602830',
    projectId: 'auth-modul-b7b48',
    authDomain: 'auth-modul-b7b48.firebaseapp.com',
    storageBucket: 'auth-modul-b7b48.firebasestorage.app',
    measurementId: 'G-Q18YQR0BJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtnvPRn-YZcqgrwT5ytH2D5qID64exSYY',
    appId: '1:833233602830:android:32298ee1303aa11855af5f',
    messagingSenderId: '833233602830',
    projectId: 'auth-modul-b7b48',
    storageBucket: 'auth-modul-b7b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJYkY5OyEJZMR9WYHqDs9y2oV3rSuNRA',
    appId: '1:833233602830:ios:e5b4af0dce854aea55af5f',
    messagingSenderId: '833233602830',
    projectId: 'auth-modul-b7b48',
    storageBucket: 'auth-modul-b7b48.firebasestorage.app',
    iosBundleId: 'com.example.awesomeNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHJYkY5OyEJZMR9WYHqDs9y2oV3rSuNRA',
    appId: '1:833233602830:ios:e5b4af0dce854aea55af5f',
    messagingSenderId: '833233602830',
    projectId: 'auth-modul-b7b48',
    storageBucket: 'auth-modul-b7b48.firebasestorage.app',
    iosBundleId: 'com.example.awesomeNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2eCrAhpshFdyU2ie90nq41riZcyqk6s8',
    appId: '1:833233602830:web:657020324397c17955af5f',
    messagingSenderId: '833233602830',
    projectId: 'auth-modul-b7b48',
    authDomain: 'auth-modul-b7b48.firebaseapp.com',
    storageBucket: 'auth-modul-b7b48.firebasestorage.app',
    measurementId: 'G-RLE0S7M739',
  );

}